### ISSUE TITLE
Couldn't open pdf file

### ISSUE THREAD

**Issue by eloureiro** [digithree/scaffold-card-game#1]
I've tried to open the pdf files with various software and receive the message the file is damaged.

**Comment by digithree** [comment]
Hi @eloureiro , thank you for your interest. I have checked the PDF but I am able to open it without issue, both in browser and on mac, and on Android device. I cannot check it on Windows or Linux right now but I would expect it to also work with a standard PDF viewer.

In case your problem persists, and for more flexibility, I have now also included some additional export formats:

* EPUB
* JPG
* PNG

I hope at least you can access it via the image formats.

**Comment by eloureiro** [comment]
Thanks. :)
